{{- if not .Values.routeros.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "routeros-dns-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routeros-dns-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.routeros.password | required "routeros.password or routeros.existingSecret is required" | quote }}
{{- end }}
